// ==================== قاعدة بيانات دول العالم والمدن الإسلامية الشاملة ====================

// 1. كافة دول العالم بلا استثناء (~195 دولة) باللغتين العربية والإنجليزية مع الأعلام
const WORLD_COUNTRIES = [
  { code: 'all', nameAr: 'جميع الدول', nameEn: 'All Countries', flag: '🌐' },
  // دول الوطن العربي
  { code: 'SA', nameAr: 'المملكة العربية السعودية', nameEn: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'YE', nameAr: 'اليمن', nameEn: 'Yemen', flag: '🇾🇪' },
  { code: 'EG', nameAr: 'مصر', nameEn: 'Egypt', flag: '🇪🇬' },
  { code: 'AE', nameAr: 'الإمارات العربية المتحدة', nameEn: 'United Arab Emirates', flag: '🇦🇪' },
  { code: 'KW', nameAr: 'الكويت', nameEn: 'Kuwait', flag: '🇰🇼' },
  { code: 'OM', nameAr: 'عُمان', nameEn: 'Oman', flag: '🇴🇲' },
  { code: 'QA', nameAr: 'قطر', nameEn: 'Qatar', flag: '🇶🇦' },
  { code: 'BH', nameAr: 'البحرين', nameEn: 'Bahrain', flag: '🇧🇭' },
  { code: 'JO', nameAr: 'الأردن', nameEn: 'Jordan', flag: '🇯🇴' },
  { code: 'PS', nameAr: 'فلسطين', nameEn: 'Palestine', flag: '🇵🇸' },
  { code: 'SY', nameAr: 'سوريا', nameEn: 'Syria', flag: '🇸🇾' },
  { code: 'IQ', nameAr: 'العراق', nameEn: 'Iraq', flag: '🇮🇶' },
  { code: 'LB', nameAr: 'لبنان', nameEn: 'Lebanon', flag: '🇱🇧' },
  { code: 'SD', nameAr: 'السودان', nameEn: 'Sudan', flag: '🇸🇩' },
  { code: 'LY', nameAr: 'ليبيا', nameEn: 'Libya', flag: '🇱🇾' },
  { code: 'MA', nameAr: 'المغرب', nameEn: 'Morocco', flag: '🇲🇦' },
  { code: 'DZ', nameAr: 'الجزائر', nameEn: 'Algeria', flag: '🇩🇿' },
  { code: 'TN', nameAr: 'تونس', nameEn: 'Tunisia', flag: '🇹🇳' },
  { code: 'MR', nameAr: 'موريتانيا', nameEn: 'Mauritania', flag: '🇲🇷' },
  { code: 'SO', nameAr: 'الصومال', nameEn: 'Somalia', flag: '🇸🇴' },
  { code: 'DJ', nameAr: 'جيبوتي', nameEn: 'Djibouti', flag: '🇩🇯' },
  { code: 'KM', nameAr: 'جزر القمر', nameEn: 'Comoros', flag: '🇰🇲' },

  // دول آسيا والإسلامية الكبرى
  { code: 'TR', nameAr: 'تركيا', nameEn: 'Turkey', flag: '🇹🇷' },
  { code: 'ID', nameAr: 'إندونيسيا', nameEn: 'Indonesia', flag: '🇮🇩' },
  { code: 'MY', nameAr: 'ماليزيا', nameEn: 'Malaysia', flag: '🇲🇾' },
  { code: 'PK', nameAr: 'باكستان', nameEn: 'Pakistan', flag: '🇵🇰' },
  { code: 'BD', nameAr: 'بنغلاديش', nameEn: 'Bangladesh', flag: '🇧🇩' },
  { code: 'AF', nameAr: 'أفغانستان', nameEn: 'Afghanistan', flag: '🇦🇫' },
  { code: 'IR', nameAr: 'إيران', nameEn: 'Iran', flag: '🇮🇷' },
  { code: 'AZ', nameAr: 'أذربيجان', nameEn: 'Azerbaijan', flag: '🇦🇿' },
  { code: 'KZ', nameAr: 'كازاخستان', nameEn: 'Kazakhstan', flag: '🇰🇿' },
  { code: 'UZ', nameAr: 'أوزبكستان', nameEn: 'Uzbekistan', flag: '🇺🇿' },
  { code: 'TM', nameAr: 'تركمانستان', nameEn: 'Turkmenistan', flag: '🇹🇲' },
  { code: 'TJ', nameAr: 'طاجيكستان', nameEn: 'Tajikistan', flag: '🇹🇯' },
  { code: 'KG', nameAr: 'قيرغيزستان', nameEn: 'Kyrgyzstan', flag: '🇰🇬' },
  { code: 'MV', nameAr: 'المالديف', nameEn: 'Maldives', flag: '🇲🇻' },
  { code: 'BN', nameAr: 'بروناي', nameEn: 'Brunei', flag: '🇧🇳' },
  { code: 'IN', nameAr: 'الهند', nameEn: 'India', flag: '🇮🇳' },
  { code: 'CN', nameAr: 'الصين', nameEn: 'China', flag: '🇨🇳' },
  { code: 'JP', nameAr: 'اليابان', nameEn: 'Japan', flag: '🇯🇵' },
  { code: 'KR', nameAr: 'كوريا الجنوبية', nameEn: 'South Korea', flag: '🇰🇷' },
  { code: 'KP', nameAr: 'كوريا الشمالية', nameEn: 'North Korea', flag: '🇰🇵' },
  { code: 'PH', nameAr: 'الفلبين', nameEn: 'Philippines', flag: '🇵🇭' },
  { code: 'TH', nameAr: 'تايلاند', nameEn: 'Thailand', flag: '🇹🇭' },
  { code: 'VN', nameAr: 'فيتنام', nameEn: 'Vietnam', flag: '🇻🇳' },
  { code: 'SG', nameAr: 'سنغافورة', nameEn: 'Singapore', flag: '🇸🇬' },
  { code: 'LK', nameAr: 'سريلانكا', nameEn: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'NP', nameAr: 'نيبال', nameEn: 'Nepal', flag: '🇳🇵' },
  { code: 'MM', nameAr: 'ميانمار', nameEn: 'Myanmar', flag: '🇲🇲' },
  { code: 'KH', nameAr: 'كمبوديا', nameEn: 'Cambodia', flag: '🇰🇭' },
  { code: 'LA', nameAr: 'لاوس', nameEn: 'Laos', flag: '🇱🇦' },
  { code: 'MN', nameAr: 'منغوليا', nameEn: 'Mongolia', flag: '🇲🇳' },
  { code: 'BT', nameAr: 'بوتان', nameEn: 'Bhutan', flag: '🇧🇹' },
  { code: 'TL', nameAr: 'تيمور الشرقية', nameEn: 'Timor-Leste', flag: '🇹🇱' },

  // دول أوروبا
  { code: 'GB', nameAr: 'المملكة المتحدة (بريطانيا)', nameEn: 'United Kingdom', flag: '🇬🇧' },
  { code: 'FR', nameAr: 'فرنسا', nameEn: 'France', flag: '🇫🇷' },
  { code: 'DE', nameAr: 'ألمانيا', nameEn: 'Germany', flag: '🇩🇪' },
  { code: 'IT', nameAr: 'إيطاليا', nameEn: 'Italy', flag: '🇮🇹' },
  { code: 'ES', nameAr: 'إسبانيا', nameEn: 'Spain', flag: '🇪🇸' },
  { code: 'RU', nameAr: 'روسيا', nameEn: 'Russia', flag: '🇷🇺' },
  { code: 'NL', nameAr: 'هولندا', nameEn: 'Netherlands', flag: '🇳🇱' },
  { code: 'BE', nameAr: 'بلجيكا', nameEn: 'Belgium', flag: '🇧🇪' },
  { code: 'CH', nameAr: 'سويسرا', nameEn: 'Switzerland', flag: '🇨🇭' },
  { code: 'SE', nameAr: 'السويد', nameEn: 'Sweden', flag: '🇸🇪' },
  { code: 'NO', nameAr: 'النرويج', nameEn: 'Norway', flag: '🇳🇴' },
  { code: 'DK', nameAr: 'الدنمارك', nameEn: 'Denmark', flag: '🇩🇰' },
  { code: 'FI', nameAr: 'فنلندا', nameEn: 'Finland', flag: '🇫🇮' },
  { code: 'IE', nameAr: 'أيرلندا', nameEn: 'Ireland', flag: '🇮🇪' },
  { code: 'AT', nameAr: 'النمسا', nameEn: 'Austria', flag: '🇦🇹' },
  { code: 'GR', nameAr: 'اليونان', nameEn: 'Greece', flag: '🇬🇷' },
  { code: 'PT', nameAr: 'البرتغال', nameEn: 'Portugal', flag: '🇵🇹' },
  { code: 'PL', nameAr: 'بولندا', nameEn: 'Poland', flag: '🇵🇱' },
  { code: 'UA', nameAr: 'أوكرانيا', nameEn: 'Ukraine', flag: '🇺🇦' },
  { code: 'RO', nameAr: 'رومانيا', nameEn: 'Romania', flag: '🇷🇴' },
  { code: 'CZ', nameAr: 'التشيك', nameEn: 'Czech Republic', flag: '🇨🇿' },
  { code: 'HU', nameAr: 'المجر', nameEn: 'Hungary', flag: '🇭🇺' },
  { code: 'BY', nameAr: 'بيلاروسيا', nameEn: 'Belarus', flag: '🇧🇾' },
  { code: 'BG', nameAr: 'بلغاريا', nameEn: 'Bulgaria', flag: '🇧🇬' },
  { code: 'RS', nameAr: 'صربيا', nameEn: 'Serbia', flag: '🇷🇸' },
  { code: 'BA', nameAr: 'البوسنة والهرسك', nameEn: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { code: 'AL', nameAr: 'ألبانيا', nameEn: 'Albania', flag: '🇦🇱' },
  { code: 'HR', nameAr: 'كرواتيا', nameEn: 'Croatia', flag: '🇭🇷' },
  { code: 'SK', nameAr: 'سلوفاكيا', nameEn: 'Slovakia', flag: '🇸🇰' },
  { code: 'SI', nameAr: 'سلوفينيا', nameEn: 'Slovenia', flag: '🇸🇮' },
  { code: 'MK', nameAr: 'مقدونيا الشمالية', nameEn: 'North Macedonia', flag: '🇲🇰' },
  { code: 'XK', nameAr: 'كوسوفو', nameEn: 'Kosovo', flag: '🇽🇰' },
  { code: 'ME', nameAr: 'الجبل الأسود', nameEn: 'Montenegro', flag: '🇲🇪' },
  { code: 'CY', nameAr: 'قبرص', nameEn: 'Cyprus', flag: '🇨🇾' },
  { code: 'LU', nameAr: 'لوكسمبورغ', nameEn: 'Luxembourg', flag: '🇱🇺' },
  { code: 'IS', nameAr: 'آيسلندا', nameEn: 'Iceland', flag: '🇮🇸' },
  { code: 'MT', nameAr: 'مالطا', nameEn: 'Malta', flag: '🇲🇹' },
  { code: 'EE', nameAr: 'إستونيا', nameEn: 'Estonia', flag: '🇪🇪' },
  { code: 'LV', nameAr: 'لاتفيا', nameEn: 'Latvia', flag: '🇱🇻' },
  { code: 'LT', nameAr: 'ليتوانيا', nameEn: 'Lithuania', flag: '🇱🇹' },
  { code: 'MD', nameAr: 'مولدوفا', nameEn: 'Moldova', flag: '🇲🇩' },
  { code: 'GE', nameAr: 'جورجيا', nameEn: 'Georgia', flag: '🇬🇪' },
  { code: 'AM', nameAr: 'أرمينيا', nameEn: 'Armenia', flag: '🇦🇲' },
  { code: 'MC', nameAr: 'موناكو', nameEn: 'Monaco', flag: '🇲🇨' },
  { code: 'LI', nameAr: 'ليختنشتاين', nameEn: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'SM', nameAr: 'سان مارينو', nameEn: 'San Marino', flag: '🇸🇲' },
  { code: 'AD', nameAr: 'أندورا', nameEn: 'Andorra', flag: '🇦🇩' },
  { code: 'VA', nameAr: 'الفاتيكان', nameEn: 'Vatican City', flag: '🇻🇦' },

  // دول الأمريكتين
  { code: 'US', nameAr: 'الولايات المتحدة الأمريكية', nameEn: 'United States', flag: '🇺🇸' },
  { code: 'CA', nameAr: 'كندا', nameEn: 'Canada', flag: '🇨🇦' },
  { code: 'BR', nameAr: 'البرازيل', nameEn: 'Brazil', flag: '🇧🇷' },
  { code: 'MX', nameAr: 'المكسيك', nameEn: 'Mexico', flag: '🇲🇽' },
  { code: 'AR', nameAr: 'الأرجنتين', nameEn: 'Argentina', flag: '🇦🇷' },
  { code: 'CO', nameAr: 'كولومبيا', nameEn: 'Colombia', flag: '🇨🇴' },
  { code: 'CL', nameAr: 'تشيلي', nameEn: 'Chile', flag: '🇨🇱' },
  { code: 'PE', nameAr: 'بيرو', nameEn: 'Peru', flag: '🇵🇪' },
  { code: 'VE', nameAr: 'فنزويلا', nameEn: 'Venezuela', flag: '🇻🇪' },
  { code: 'EC', nameAr: 'الإكوادور', nameEn: 'Ecuador', flag: '🇪🇨' },
  { code: 'BO', nameAr: 'بوليفيا', nameEn: 'Bolivia', flag: '🇧🇴' },
  { code: 'PY', nameAr: 'باراغواي', nameEn: 'Paraguay', flag: '🇵🇾' },
  { code: 'UY', nameAr: 'أوروغواي', nameEn: 'Uruguay', flag: '🇺🇾' },
  { code: 'GY', nameAr: 'غيانا', nameEn: 'Guyana', flag: '🇬🇾' },
  { code: 'SR', nameAr: 'سورينام', nameEn: 'Suriname', flag: '🇸🇷' },
  { code: 'CU', nameAr: 'كوبا', nameEn: 'Cuba', flag: '🇨🇺' },
  { code: 'DO', nameAr: 'جمهورية الدومينيكان', nameEn: 'Dominican Republic', flag: '🇩🇴' },
  { code: 'HT', nameAr: 'هايتي', nameEn: 'Haiti', flag: '🇭🇹' },
  { code: 'JM', nameAr: 'جامايكا', nameEn: 'Jamaica', flag: '🇯🇲' },
  { code: 'TT', nameAr: 'ترينيداد وتوباغو', nameEn: 'Trinidad and Tobago', flag: '🇹🇹' },
  { code: 'PA', nameAr: 'بنما', nameEn: 'Panama', flag: '🇵🇦' },
  { code: 'CR', nameAr: 'كوستاريكا', nameEn: 'Costa Rica', flag: '🇨🇷' },
  { code: 'NI', nameAr: 'نيكاراغوا', nameEn: 'Nicaragua', flag: '🇳🇮' },
  { code: 'HN', nameAr: 'هندوراس', nameEn: 'Honduras', flag: '🇭🇳' },
  { code: 'SV', nameAr: 'السلفادور', nameEn: 'El Salvador', flag: '🇸🇻' },
  { code: 'GT', nameAr: 'غواتيمالا', nameEn: 'Guatemala', flag: '🇬🇹' },
  { code: 'BZ', nameAr: 'بليز', nameEn: 'Belize', flag: '🇧🇿' },
  { code: 'BS', nameAr: 'البهاما', nameEn: 'Bahamas', flag: '🇧🇸' },
  { code: 'BB', nameAr: 'باربادوس', nameEn: 'Barbados', flag: '🇧🇧' },

  // دول أفريقيا
  { code: 'NG', nameAr: 'نيجيريا', nameEn: 'Nigeria', flag: '🇳🇬' },
  { code: 'ET', nameAr: 'إثيوبيا', nameEn: 'Ethiopia', flag: '🇪🇹' },
  { code: 'ZA', nameAr: 'جنوب أفريقيا', nameEn: 'South Africa', flag: '🇿🇦' },
  { code: 'KE', nameAr: 'كينيا', nameEn: 'Kenya', flag: '🇰🇪' },
  { code: 'UG', nameAr: 'أوغندا', nameEn: 'Uganda', flag: '🇺🇬' },
  { code: 'TZ', nameAr: 'تنزانيا', nameEn: 'Tanzania', flag: '🇹🇿' },
  { code: 'GH', nameAr: 'غانا', nameEn: 'Ghana', flag: '🇬🇭' },
  { code: 'CI', nameAr: 'ساحل العاج', nameEn: 'Ivory Coast', flag: '🇨🇮' },
  { code: 'SN', nameAr: 'السنغال', nameEn: 'Senegal', flag: '🇸🇳' },
  { code: 'ML', nameAr: 'مالي', nameEn: 'Mali', flag: '🇲🇱' },
  { code: 'NE', nameAr: 'النيجر', nameEn: 'Niger', flag: '🇳🇪' },
  { code: 'TD', nameAr: 'تشاد', nameEn: 'Chad', flag: '🇹🇩' },
  { code: 'GN', nameAr: 'غينيا', nameEn: 'Guinea', flag: '🇬🇳' },
  { code: 'BF', nameAr: 'بوركينا فاسو', nameEn: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'CM', nameAr: 'الكاميرون', nameEn: 'Cameroon', flag: '🇨🇲' },
  { code: 'AO', nameAr: 'أنغولا', nameEn: 'Angola', flag: '🇦🇴' },
  { code: 'MZ', nameAr: 'موزمبيق', nameEn: 'Mozambique', flag: '🇲🇿' },
  { code: 'ZM', nameAr: 'زامبيا', nameEn: 'Zambia', flag: '🇿🇲' },
  { code: 'ZW', nameAr: 'زيمبابوي', nameEn: 'Zimbabwe', flag: '🇿🇼' },
  { code: 'RW', nameAr: 'رواندا', nameEn: 'Rwanda', flag: '🇷🇼' },
  { code: 'BI', nameAr: 'بوروندي', nameEn: 'Burundi', flag: '🇧🇮' },
  { code: 'SS', nameAr: 'جنوب السودان', nameEn: 'South Sudan', flag: '🇸🇸' },
  { code: 'ER', nameAr: 'إريتريا', nameEn: 'Eritrea', flag: '🇪🇷' },
  { code: 'GM', nameAr: 'غامبيا', nameEn: 'Gambia', flag: '🇬🇲' },
  { code: 'SL', nameAr: 'سيراليون', nameEn: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'LR', nameAr: 'ليبيريا', nameEn: 'Liberia', flag: '🇱🇷' },
  { code: 'TG', nameAr: 'توغو', nameEn: 'Togo', flag: '🇹🇬' },
  { code: 'BJ', nameAr: 'بنين', nameEn: 'Benin', flag: '🇧🇯' },
  { code: 'GA', nameAr: 'الغابون', nameEn: 'Gabon', flag: '🇬🇦' },
  { code: 'CG', nameAr: 'جمهورية الكونغو', nameEn: 'Republic of the Congo', flag: '🇨🇬' },
  { code: 'CD', nameAr: 'الكونغو الديمقراطية', nameEn: 'DR Congo', flag: '🇨🇩' },
  { code: 'CF', nameAr: 'أفريقيا الوسطى', nameEn: 'Central African Republic', flag: '🇨🇫' },
  { code: 'GQ', nameAr: 'غينيا الاستوائية', nameEn: 'Equatorial Guinea', flag: '🇬🇶' },
  { code: 'GW', nameAr: 'غينيا بيساو', nameEn: 'Guinea-Bissau', flag: '🇬🇼' },
  { code: 'CV', nameAr: 'الرأس الأخضر', nameEn: 'Cape Verde', flag: '🇨🇻' },
  { code: 'ST', nameAr: 'ساو تومي وبرينسيب', nameEn: 'Sao Tome and Principe', flag: '🇸🇹' },
  { code: 'MG', nameAr: 'مدغشقر', nameEn: 'Madagascar', flag: '🇲🇬' },
  { code: 'MU', nameAr: 'موريشيوس', nameEn: 'Mauritius', flag: '🇲🇺' },
  { code: 'SC', nameAr: 'سيشل', nameEn: 'Seychelles', flag: '🇸🇨' },
  { code: 'BW', nameAr: 'بوتسوانا', nameEn: 'Botswana', flag: '🇧🇼' },
  { code: 'NA', nameAr: 'ناميبيا', nameEn: 'Namibia', flag: '🇳🇦' },
  { code: 'LS', nameAr: 'ليسوتو', nameEn: 'Lesotho', flag: '🇱🇸' },
  { code: 'SZ', nameAr: 'إسواتيني', nameEn: 'Eswatini', flag: '🇸🇿' },
  { code: 'MW', nameAr: 'مالاوي', nameEn: 'Malawi', flag: '🇲🇼' },

  // دول أوقيانوسيا
  { code: 'AU', nameAr: 'أستراليا', nameEn: 'Australia', flag: '🇦🇺' },
  { code: 'NZ', nameAr: 'نيوزيلندا', nameEn: 'New Zealand', flag: '🇳🇿' },
  { code: 'FJ', nameAr: 'فيجي', nameEn: 'Fiji', flag: '🇫🇯' },
  { code: 'PG', nameAr: 'بابوا غينيا الجديدة', nameEn: 'Papua New Guinea', flag: '🇵🇬' }
];

// 2. المحافظات والمدن الكاملة (اليمن، السعودية، الخليج، مصر، والعالم)
const REGION_CITIES = [
  // ==================== المملكة العربية السعودية ====================
  { name: 'مكة المكرمة', country: 'المملكة العربية السعودية', lat: 21.4225, lng: 39.8262, method: 4 },
  { name: 'المدينة المنورة', country: 'المملكة العربية السعودية', lat: 24.4672, lng: 39.6111, method: 4 },
  { name: 'الرياض', country: 'المملكة العربية السعودية', lat: 24.7136, lng: 46.6753, method: 4 },
  { name: 'الخرج', country: 'المملكة العربية السعودية', lat: 24.1554, lng: 47.3120, method: 4 },
  { name: 'جدة', country: 'المملكة العربية السعودية', lat: 21.5433, lng: 39.1728, method: 4 },
  { name: 'الدمام', country: 'المملكة العربية السعودية', lat: 26.4207, lng: 50.0888, method: 4 },
  { name: 'الخبر', country: 'المملكة العربية السعودية', lat: 26.2818, lng: 50.1989, method: 4 },
  { name: 'الظهران', country: 'المملكة العربية السعودية', lat: 26.2886, lng: 50.1140, method: 4 },
  { name: 'الأحساء (الهفوف)', country: 'المملكة العربية السعودية', lat: 25.3835, lng: 49.5862, method: 4 },
  { name: 'القطيف', country: 'المملكة العربية السعودية', lat: 26.5652, lng: 50.0109, method: 4 },
  { name: 'الجبيل', country: 'المملكة العربية السعودية', lat: 27.0046, lng: 49.6606, method: 4 },
  { name: 'حفر الباطن', country: 'المملكة العربية السعودية', lat: 28.4328, lng: 45.9708, method: 4 },
  { name: 'الخفجي', country: 'المملكة العربية السعودية', lat: 28.4391, lng: 48.4913, method: 4 },
  { name: 'بريدة (القصيم)', country: 'المملكة العربية السعودية', lat: 26.3260, lng: 43.9750, method: 4 },
  { name: 'عنيزة', country: 'المملكة العربية السعودية', lat: 26.0844, lng: 43.9936, method: 4 },
  { name: 'الرس', country: 'المملكة العربية السعودية', lat: 25.8694, lng: 43.4973, method: 4 },
  { name: 'حائل', country: 'المملكة العربية السعودية', lat: 27.5219, lng: 41.6907, method: 4 },
  { name: 'تبوك', country: 'المملكة العربية السعودية', lat: 28.3835, lng: 36.5662, method: 4 },
  { name: 'ضباء', country: 'المملكة العربية السعودية', lat: 27.2982, lng: 35.7197, method: 4 },
  { name: 'الوجه', country: 'المملكة العربية السعودية', lat: 26.2455, lng: 36.4525, method: 4 },
  { name: 'عرعر', country: 'المملكة العربية السعودية', lat: 30.9753, lng: 41.0381, method: 4 },
  { name: 'رفحاء', country: 'المملكة العربية السعودية', lat: 29.6349, lng: 43.4919, method: 4 },
  { name: 'طريف', country: 'المملكة العربية السعودية', lat: 31.6725, lng: 38.6637, method: 4 },
  { name: 'سكاكا (الجوف)', country: 'المملكة العربية السعودية', lat: 29.9697, lng: 40.2064, method: 4 },
  { name: 'القريات', country: 'المملكة العربية السعودية', lat: 31.3318, lng: 37.3428, method: 4 },
  { name: 'أبها', country: 'المملكة العربية السعودية', lat: 18.2164, lng: 42.5053, method: 4 },
  { name: 'خميس مشيط', country: 'المملكة العربية السعودية', lat: 18.3064, lng: 42.7330, method: 4 },
  { name: 'بيشة', country: 'المملكة العربية السعودية', lat: 20.0005, lng: 42.6044, method: 4 },
  { name: 'محايل عسير', country: 'المملكة العربية السعودية', lat: 18.5411, lng: 42.0514, method: 4 },
  { name: 'جازان', country: 'المملكة العربية السعودية', lat: 16.8892, lng: 42.5511, method: 4 },
  { name: 'صبيا', country: 'المملكة العربية السعودية', lat: 17.1495, lng: 42.6254, method: 4 },
  { name: 'أبو عريش', country: 'المملكة العربية السعودية', lat: 16.9698, lng: 42.8291, method: 4 },
  { name: 'صامطة', country: 'المملكة العربية السعودية', lat: 16.5960, lng: 42.9431, method: 4 },
  { name: 'نجران', country: 'المملكة العربية السعودية', lat: 17.4924, lng: 44.1277, method: 4 },
  { name: 'شرورة', country: 'المملكة العربية السعودية', lat: 17.4764, lng: 47.1206, method: 4 },
  { name: 'الباحة', country: 'المملكة العربية السعودية', lat: 20.0129, lng: 41.4677, method: 4 },
  { name: 'بلجرشي', country: 'المملكة العربية السعودية', lat: 19.8631, lng: 41.6256, method: 4 },
  { name: 'الطائف', country: 'المملكة العربية السعودية', lat: 21.2854, lng: 40.4222, method: 4 },
  { name: 'ينبع', country: 'المملكة العربية السعودية', lat: 24.0891, lng: 38.0637, method: 4 },
  { name: 'العلا', country: 'المملكة العربية السعودية', lat: 26.6167, lng: 37.9167, method: 4 },
  { name: 'وادي الدواسر', country: 'المملكة العربية السعودية', lat: 20.4500, lng: 44.8667, method: 4 },
  { name: 'الدوادمي', country: 'المملكة العربية السعودية', lat: 24.5075, lng: 44.3922, method: 4 },
  { name: 'المجمعة', country: 'المملكة العربية السعودية', lat: 25.9000, lng: 45.3333, method: 4 },
  { name: 'الزلفي', country: 'المملكة العربية السعودية', lat: 26.3000, lng: 44.8000, method: 4 },
  { name: 'شقراء', country: 'المملكة العربية السعودية', lat: 25.2500, lng: 45.2500, method: 4 },
  { name: 'القنفذة', country: 'المملكة العربية السعودية', lat: 19.1281, lng: 41.0786, method: 4 },

  // ==================== الجمهورية اليمنية (كافة المحافظات الـ 22) ====================
  { name: 'أمانة العاصمة (صنعاء)', country: 'اليمن', lat: 15.3694, lng: 44.1910, method: 4 },
  { name: 'صنعاء (المحافظة)', country: 'اليمن', lat: 15.3500, lng: 44.2000, method: 4 },
  { name: 'عدن', country: 'اليمن', lat: 12.7855, lng: 45.0187, method: 4 },
  { name: 'تعز', country: 'اليمن', lat: 13.5795, lng: 44.0209, method: 4 },
  { name: 'الحديدة', country: 'اليمن', lat: 14.7978, lng: 42.9545, method: 4 },
  { name: 'المكلا (حضرموت)', country: 'اليمن', lat: 14.5425, lng: 49.1242, method: 4 },
  { name: 'سيئون (وادي حضرموت)', country: 'اليمن', lat: 15.9431, lng: 48.7872, method: 4 },
  { name: 'إب', country: 'اليمن', lat: 13.9667, lng: 44.1667, method: 4 },
  { name: 'ذمار', country: 'اليمن', lat: 14.5428, lng: 44.4051, method: 4 },
  { name: 'مأرب', country: 'اليمن', lat: 15.4633, lng: 45.3258, method: 4 },
  { name: 'صعدة', country: 'اليمن', lat: 16.9402, lng: 43.7639, method: 4 },
  { name: 'حجة', country: 'اليمن', lat: 15.6944, lng: 43.6028, method: 4 },
  { name: 'البيضاء', country: 'اليمن', lat: 13.9852, lng: 45.5727, method: 4 },
  { name: 'عمران', country: 'اليمن', lat: 15.6594, lng: 43.9439, method: 4 },
  { name: 'الجوف (الحزم)', country: 'اليمن', lat: 16.1667, lng: 44.7667, method: 4 },
  { name: 'المحويت', country: 'اليمن', lat: 15.4700, lng: 43.5447, method: 4 },
  { name: 'شبوة (عتق)', country: 'اليمن', lat: 14.5377, lng: 46.8319, method: 4 },
  { name: 'أبين (زنجبار)', country: 'اليمن', lat: 13.1287, lng: 45.3806, method: 4 },
  { name: 'لحج (الحوطة)', country: 'اليمن', lat: 13.0583, lng: 44.8819, method: 4 },
  { name: 'الضالع', country: 'اليمن', lat: 13.6957, lng: 44.7314, method: 4 },
  { name: 'الغيضة (المهرة)', country: 'اليمن', lat: 16.2079, lng: 52.1760, method: 4 },
  { name: 'سقطرى (حديبو)', country: 'اليمن', lat: 12.6500, lng: 54.0167, method: 4 },
  { name: 'ريمة (الجبين)', country: 'اليمن', lat: 14.6500, lng: 43.6000, method: 4 },

  // ==================== جمهورية مصر العربية (كافة المحافظات الـ 27) ====================
  { name: 'القاهرة', country: 'مصر', lat: 30.0444, lng: 31.2357, method: 5 },
  { name: 'الإسكندرية', country: 'مصر', lat: 31.2001, lng: 29.9187, method: 5 },
  { name: 'الجيزة', country: 'مصر', lat: 30.0131, lng: 31.2089, method: 5 },
  { name: 'القليوبية (بنها)', country: 'مصر', lat: 30.4591, lng: 31.1786, method: 5 },
  { name: 'الدقهلية (المنصورة)', country: 'مصر', lat: 31.0409, lng: 31.3785, method: 5 },
  { name: 'الغربية (طنطا)', country: 'مصر', lat: 30.7865, lng: 31.0004, method: 5 },
  { name: 'المحلة الكبرى', country: 'مصر', lat: 30.9706, lng: 31.1669, method: 5 },
  { name: 'الشرقية (الزقازيق)', country: 'مصر', lat: 30.5877, lng: 31.5020, method: 5 },
  { name: 'المنوفية (شبين الكوم)', country: 'مصر', lat: 30.5522, lng: 31.0089, method: 5 },
  { name: 'كفر الشيخ', country: 'مصر', lat: 31.1107, lng: 30.9388, method: 5 },
  { name: 'دمياط', country: 'مصر', lat: 31.4175, lng: 31.8144, method: 5 },
  { name: 'بورسعيد', country: 'مصر', lat: 31.2653, lng: 32.3019, method: 5 },
  { name: 'الإسماعيلية', country: 'مصر', lat: 30.5965, lng: 32.2715, method: 5 },
  { name: 'السويس', country: 'مصر', lat: 29.9668, lng: 32.5498, method: 5 },
  { name: 'البحيرة (دمنهور)', country: 'مصر', lat: 31.0379, lng: 30.4725, method: 5 },
  { name: 'شمال سيناء (العريش)', country: 'مصر', lat: 31.1316, lng: 33.7984, method: 5 },
  { name: 'جنوب سيناء (شرم الشيخ)', country: 'مصر', lat: 27.9158, lng: 34.3299, method: 5 },
  { name: 'الفيوم', country: 'مصر', lat: 29.3084, lng: 30.8428, method: 5 },
  { name: 'بني سويف', country: 'مصر', lat: 29.0661, lng: 31.0994, method: 5 },
  { name: 'المنيا', country: 'مصر', lat: 28.1099, lng: 30.7503, method: 5 },
  { name: 'أسيوط', country: 'مصر', lat: 27.1783, lng: 31.1859, method: 5 },
  { name: 'سوهاج', country: 'مصر', lat: 26.5590, lng: 31.6957, method: 5 },
  { name: 'قنا', country: 'مصر', lat: 26.1551, lng: 32.7160, method: 5 },
  { name: 'الأقصر', country: 'مصر', lat: 25.6872, lng: 32.6396, method: 5 },
  { name: 'أسوان', country: 'مصر', lat: 24.0889, lng: 32.8998, method: 5 },
  { name: 'البحر الأحمر (الغردقة)', country: 'مصر', lat: 27.2579, lng: 33.8116, method: 5 },
  { name: 'الوادي الجديد (الخارجة)', country: 'مصر', lat: 25.4514, lng: 30.5472, method: 5 },
  { name: 'مطروح (مرسى مطروح)', country: 'مصر', lat: 31.3543, lng: 27.2373, method: 5 },

  // ==================== الإمارات العربية المتحدة (كافة الإمارات الـ 7) ====================
  { name: 'أبوظبي', country: 'الإمارات العربية المتحدة', lat: 24.4539, lng: 54.3773, method: 4 },
  { name: 'دبي', country: 'الإمارات العربية المتحدة', lat: 25.2048, lng: 55.2708, method: 4 },
  { name: 'الشارقة', country: 'الإمارات العربية المتحدة', lat: 25.3463, lng: 55.4209, method: 4 },
  { name: 'عجمان', country: 'الإمارات العربية المتحدة', lat: 25.4052, lng: 55.5136, method: 4 },
  { name: 'رأس الخيمة', country: 'الإمارات العربية المتحدة', lat: 25.6741, lng: 55.9804, method: 4 },
  { name: 'الفجيرة', country: 'الإمارات العربية المتحدة', lat: 25.1288, lng: 56.3265, method: 4 },
  { name: 'أم القيوين', country: 'الإمارات العربية المتحدة', lat: 25.5647, lng: 55.5532, method: 4 },
  { name: 'العين', country: 'الإمارات العربية المتحدة', lat: 24.1302, lng: 55.8023, method: 4 },

  // ==================== الكويت (كافة المحافظات الـ 6) ====================
  { name: 'الكويت (العاصمة)', country: 'الكويت', lat: 29.3759, lng: 47.9774, method: 4 },
  { name: 'حولي', country: 'الكويت', lat: 29.3328, lng: 48.0282, method: 4 },
  { name: 'الفروانية', country: 'الكويت', lat: 29.2778, lng: 47.9583, method: 4 },
  { name: 'الأحمدي', country: 'الكويت', lat: 29.0769, lng: 48.0839, method: 4 },
  { name: 'الجهراء', country: 'الكويت', lat: 29.3375, lng: 47.6581, method: 4 },
  { name: 'مبارك الكبير', country: 'الكويت', lat: 29.2361, lng: 48.0556, method: 4 },

  // ==================== قطر (كافة البلديات الرئيسية) ====================
  { name: 'الدوحة', country: 'قطر', lat: 25.2854, lng: 51.5310, method: 4 },
  { name: 'الريان', country: 'قطر', lat: 25.2919, lng: 51.4244, method: 4 },
  { name: 'الوكرة', country: 'قطر', lat: 25.1768, lng: 51.6048, method: 4 },
  { name: 'الخور', country: 'قطر', lat: 25.6839, lng: 51.5058, method: 4 },
  { name: 'أم صلال', country: 'قطر', lat: 25.4167, lng: 51.4000, method: 4 },
  { name: 'الشحانية', country: 'قطر', lat: 25.3708, lng: 51.2269, method: 4 },
  { name: 'الشمال', country: 'قطر', lat: 26.1158, lng: 51.2181, method: 4 },

  // ==================== مملكة البحرين ====================
  { name: 'المنامة', country: 'البحرين', lat: 26.2285, lng: 50.5860, method: 4 },
  { name: 'المحرق', country: 'البحرين', lat: 26.2572, lng: 50.6119, method: 4 },
  { name: 'الرفاع', country: 'البحرين', lat: 26.1300, lng: 50.5550, method: 4 },
  { name: 'مدينة حمد', country: 'البحرين', lat: 26.1153, lng: 50.5069, method: 4 },
  { name: 'مدينة عيسى', country: 'البحرين', lat: 26.1736, lng: 50.5478, method: 4 },

  // ==================== سلطنة عُمان (كافة المحافظات الرئيسية) ====================
  { name: 'مسقط', country: 'عُمان', lat: 23.5880, lng: 58.3829, method: 4 },
  { name: 'صلالة (ظفار)', country: 'عُمان', lat: 17.0151, lng: 54.0924, method: 4 },
  { name: 'صحار (شمال الباطنة)', country: 'عُمان', lat: 24.3461, lng: 56.7075, method: 4 },
  { name: 'الرستاق (جنوب الباطنة)', country: 'عُمان', lat: 23.3908, lng: 57.4244, method: 4 },
  { name: 'نزوى (الداخلية)', country: 'عُمان', lat: 22.9333, lng: 57.5333, method: 4 },
  { name: 'صور (جنوب الشرقية)', country: 'عُمان', lat: 22.5667, lng: 59.5289, method: 4 },
  { name: 'إبراء (شمال الشرقية)', country: 'عُمان', lat: 22.6906, lng: 58.5333, method: 4 },
  { name: 'عبري (الظاهرة)', country: 'عُمان', lat: 23.2257, lng: 56.5157, method: 4 },
  { name: 'خصب (مسندم)', country: 'عُمان', lat: 26.1799, lng: 56.2477, method: 4 },
  { name: 'البريمي', country: 'عُمان', lat: 24.2509, lng: 55.7931, method: 4 },
  { name: 'هيما (الوسطى)', country: 'عُمان', lat: 19.9592, lng: 56.2758, method: 4 },

  // ==================== باقي الدول العربية (أكبر المدن والعواصم) ====================
  // فلسطين
  { name: 'القدس الشريف', country: 'فلسطين', lat: 31.7683, lng: 35.2137, method: 3 },
  { name: 'غزة', country: 'فلسطين', lat: 31.5017, lng: 34.4668, method: 3 },
  { name: 'رام الله', country: 'فلسطين', lat: 31.9038, lng: 35.2034, method: 3 },
  { name: 'الخليل', country: 'فلسطين', lat: 31.5326, lng: 35.0998, method: 3 },
  { name: 'نابلس', country: 'فلسطين', lat: 32.2211, lng: 35.2544, method: 3 },
  // الأردن
  { name: 'عمّان', country: 'الأردن', lat: 31.9454, lng: 35.9284, method: 3 },
  { name: 'إربد', country: 'الأردن', lat: 32.5568, lng: 35.8469, method: 3 },
  { name: 'الزرقاء', country: 'الأردن', lat: 32.0728, lng: 36.0880, method: 3 },
  { name: 'العقبة', country: 'الأردن', lat: 29.5320, lng: 35.0063, method: 3 },
  // سوريا
  { name: 'دمشق', country: 'سوريا', lat: 33.5138, lng: 36.2765, method: 3 },
  { name: 'حلب', country: 'سوريا', lat: 36.2021, lng: 37.1343, method: 3 },
  { name: 'حمص', country: 'سوريا', lat: 34.7324, lng: 36.7137, method: 3 },
  { name: 'اللاذقية', country: 'سوريا', lat: 35.5317, lng: 35.7900, method: 3 },
  // العراق
  { name: 'بغداد', country: 'العراق', lat: 33.3152, lng: 44.3661, method: 3 },
  { name: 'الموصل', country: 'العراق', lat: 36.3400, lng: 43.1300, method: 3 },
  { name: 'البصرة', country: 'العراق', lat: 30.5085, lng: 47.7804, method: 3 },
  { name: 'أربيل', country: 'العراق', lat: 36.1911, lng: 44.0092, method: 3 },
  // لبنان
  { name: 'بيروت', country: 'لبنان', lat: 33.8938, lng: 35.5018, method: 3 },
  { name: 'طرابلس (لبنان)', country: 'لبنان', lat: 34.4367, lng: 35.8497, method: 3 },
  { name: 'صيدا', country: 'لبنان', lat: 33.5631, lng: 35.3689, method: 3 },
  // السودان
  { name: 'الخرطوم', country: 'السودان', lat: 15.5007, lng: 32.5599, method: 5 },
  { name: 'أم درمان', country: 'السودان', lat: 15.6500, lng: 32.4833, method: 5 },
  { name: 'بورتسودان', country: 'السودان', lat: 19.6167, lng: 37.2167, method: 5 },
  // ليبيا
  { name: 'طرابلس (ليبيا)', country: 'ليبيا', lat: 32.8872, lng: 13.1913, method: 3 },
  { name: 'بنغازي', country: 'ليبيا', lat: 32.1167, lng: 20.0667, method: 3 },
  { name: 'مصراتة', country: 'ليبيا', lat: 32.3754, lng: 15.0925, method: 3 },
  // المغرب
  { name: 'الرباط', country: 'المغرب', lat: 34.0209, lng: -6.8416, method: 3 },
  { name: 'الدار البيضاء', country: 'المغرب', lat: 33.5731, lng: -7.5898, method: 3 },
  { name: 'فاس', country: 'المغرب', lat: 34.0333, lng: -5.0000, method: 3 },
  { name: 'مراكش', country: 'المغرب', lat: 31.6295, lng: -7.9811, method: 3 },
  { name: 'طنجة', country: 'المغرب', lat: 35.7595, lng: -5.8340, method: 3 },
  // الجزائر
  { name: 'الجزائر العاصمة', country: 'الجزائر', lat: 36.7538, lng: 3.0588, method: 3 },
  { name: 'وهران', country: 'الجزائر', lat: 35.6971, lng: -0.6308, method: 3 },
  { name: 'قسنطينة', country: 'الجزائر', lat: 36.3650, lng: 6.6147, method: 3 },
  // تونس
  { name: 'تونس (العاصمة)', country: 'تونس', lat: 36.8065, lng: 10.1815, method: 3 },
  { name: 'صفاقس', country: 'تونس', lat: 34.7406, lng: 10.7603, method: 3 },
  { name: 'سوسة', country: 'تونس', lat: 35.8256, lng: 10.6369, method: 3 },
  // موريتانيا والصومال وجيبوتي
  { name: 'نواكشوط', country: 'موريتانيا', lat: 18.0735, lng: -15.9582, method: 3 },
  { name: 'مقديشو', country: 'الصومال', lat: 2.0469, lng: 45.3182, method: 3 },
  { name: 'جيبوتي (العاصمة)', country: 'جيبوتي', lat: 11.5721, lng: 43.1456, method: 3 },
  { name: 'موروني', country: 'جزر القمر', lat: -11.7172, lng: 43.2473, method: 3 },

  // ==================== دول إسلامية وعالمية كبرى ====================
  { name: 'إسطنبول', country: 'تركيا', lat: 41.0082, lng: 28.9784, method: 13 },
  { name: 'أنقرة', country: 'تركيا', lat: 39.9334, lng: 32.8597, method: 13 },
  { name: 'جاكرتا', country: 'إندونيسيا', lat: -6.2088, lng: 106.8456, method: 11 },
  { name: 'كوالالمبور', country: 'ماليزيا', lat: 3.1390, lng: 101.6869, method: 11 },
  { name: 'إسلام آباد', country: 'باكستان', lat: 33.6844, lng: 73.0479, method: 1 },
  { name: 'كراتشي', country: 'باكستان', lat: 24.8607, lng: 67.0011, method: 1 },
  { name: 'دكا', country: 'بنغلاديش', lat: 23.8103, lng: 90.4125, method: 1 },
  { name: 'لندن', country: 'المملكة المتحدة (بريطانيا)', lat: 51.5074, lng: -0.1278, method: 3 },
  { name: 'مانشستر', country: 'المملكة المتحدة (بريطانيا)', lat: 53.4808, lng: -2.2426, method: 3 },
  { name: 'برمنغهام', country: 'المملكة المتحدة (بريطانيا)', lat: 52.4862, lng: -1.8904, method: 3 },
  { name: 'واشنطن', country: 'الولايات المتحدة الأمريكية', lat: 38.9072, lng: -77.0369, method: 2 },
  { name: 'نيويورك', country: 'الولايات المتحدة الأمريكية', lat: 40.7128, lng: -74.0060, method: 2 },
  { name: 'شيكاغو', country: 'الولايات المتحدة الأمريكية', lat: 41.8781, lng: -87.6298, method: 2 },
  { name: 'لوس أنجلوس', country: 'الولايات المتحدة الأمريكية', lat: 34.0522, lng: -118.2437, method: 2 },
  { name: 'باريس', country: 'فرنسا', lat: 48.8566, lng: 2.3522, method: 12 },
  { name: 'مارسيليا', country: 'فرنسا', lat: 43.2965, lng: 5.3698, method: 12 },
  { name: 'برلين', country: 'ألمانيا', lat: 52.5200, lng: 13.4050, method: 3 },
  { name: 'فرانكفورت', country: 'ألمانيا', lat: 50.1109, lng: 8.6821, method: 3 },
  { name: 'تورونتو', country: 'كندا', lat: 43.6532, lng: -79.3832, method: 2 },
  { name: 'سيدني', country: 'أستراليا', lat: -33.8688, lng: 151.2093, method: 3 },
  { name: 'موسكو', country: 'روسيا', lat: 55.7558, lng: 37.6173, method: 3 },
  { name: 'قازان', country: 'روسيا', lat: 55.8304, lng: 49.0661, method: 3 }
];
